//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GammaX_Switcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GammaX_Switcher.Properties.Resources.zh-CN", typeof(Resources_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有颜色.
        /// </summary>
        internal static string buttonAllColors {
            get {
                return ResourceManager.GetString("buttonAllColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蓝色.
        /// </summary>
        internal static string buttonBlue {
            get {
                return ResourceManager.GetString("buttonBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一个.
        /// </summary>
        internal static string buttonForward {
            get {
                return ResourceManager.GetString("buttonForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绿色.
        /// </summary>
        internal static string buttonGreen {
            get {
                return ResourceManager.GetString("buttonGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏.
        /// </summary>
        internal static string buttonHide {
            get {
                return ResourceManager.GetString("buttonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 红色.
        /// </summary>
        internal static string buttonRed {
            get {
                return ResourceManager.GetString("buttonRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置.
        /// </summary>
        internal static string buttonReset {
            get {
                return ResourceManager.GetString("buttonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +++.
        /// </summary>
        internal static string checkBoxExContrast {
            get {
                return ResourceManager.GetString("checkBoxExContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示器.
        /// </summary>
        internal static string comboBoxMonitors {
            get {
                return ResourceManager.GetString("comboBoxMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预设.
        /// </summary>
        internal static string comboBoxPresets {
            get {
                return ResourceManager.GetString("comboBoxPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亮度.
        /// </summary>
        internal static string labelBrightness {
            get {
                return ResourceManager.GetString("labelBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对比度.
        /// </summary>
        internal static string labelContrast {
            get {
                return ResourceManager.GetString("labelContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伽马值.
        /// </summary>
        internal static string labelGamma {
            get {
                return ResourceManager.GetString("labelGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入快捷键.
        /// </summary>
        internal static string labelHotkeyTip {
            get {
                return ResourceManager.GetString("labelHotkeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string labelLanguage {
            get {
                return ResourceManager.GetString("labelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亮度.
        /// </summary>
        internal static string labelMonitorBrightnessDown {
            get {
                return ResourceManager.GetString("labelMonitorBrightnessDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示器.
        /// </summary>
        internal static string labelMonitorBrightnessUp {
            get {
                return ResourceManager.GetString("labelMonitorBrightnessUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对比度.
        /// </summary>
        internal static string labelMonitorContrastDown {
            get {
                return ResourceManager.GetString("labelMonitorContrastDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示器.
        /// </summary>
        internal static string labelMonitorContrastUp {
            get {
                return ResourceManager.GetString("labelMonitorContrastUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伽马值管理器.
        /// </summary>
        internal static string notifyIcon_Text {
            get {
                return ResourceManager.GetString("notifyIcon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string txtExit {
            get {
                return ResourceManager.GetString("txtExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string txtSettings {
            get {
                return ResourceManager.GetString("txtSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伽马值管理器.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
